version: "3.9"
services:

  kubefill-postgres:
    image: postgres:13.1
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  kubefill-repo-server:
    image: kubefill/workspace:latest
    platform: linux/x86_64
    working_dir: /home/kubefill/cmd
    ports:
      - 8081:8081
    tty: true
    stdin_open: true
    command: go run main.go
    volumes:
      - ./logs:/home/kubefill/logs
      - ./repos:/home/kubefill/repos
      - ./ssh:/home/kubefill/.ssh

      - ./wsserver:/home/kubefill/wsserver
      - ./server:/home/kubefill/server
      - ./reposerver:/home/kubefill/reposerver

      - ./cmd:/home/kubefill/cmd
      - ./common:/home/kubefill/common
      - ./pkg:/home/kubefill/pkg
      - ./ui:/home/kubefill/ui
      - ./util:/home/kubefill/util

      - ./embed.go:/home/kubefill/embed.go
      - ./go.mod:/home/kubefill/go.mod
      - ./go.sum:/home/kubefill/go.sum

    environment:
      - BINARY_NAME=kubefill-reposerver
      - HOME=/home/kubefill

      - REPO_ROOT=/home/kubefill/repos
      - SSH_ROOT=/home/kubefill/.ssh
      - SSH_KNOWN_HOSTS=/home/kubefill/.ssh/know_hosts

  kubefill-server:
    image: kubefill/workspace:latest
    platform: linux/x86_64
    working_dir: /home/kubefill/cmd
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    command: go run main.go
    volumes:
      - ./logs:/home/kubefill/logs

      - ./wsserver:/home/kubefill/wsserver
      - ./server:/home/kubefill/server
      - ./reposerver:/home/kubefill/reposerver

      - ./cmd:/home/kubefill/cmd
      - ./common:/home/kubefill/common
      - ./pkg:/home/kubefill/pkg
      - ./ui:/home/kubefill/ui
      - ./util:/home/kubefill/util

      - ./embed.go:/home/kubefill/embed.go
      - ./go.mod:/home/kubefill/go.mod
      - ./go.sum:/home/kubefill/go.sum

      - ~/.kube/config:/home/kubefill/.kube/config

    environment:
      - BINARY_NAME=kubefill-server
      - HOME=/home/kubefill

      - SECRETS_KEY=
      - LOGS_PATH=/home/kubefill/logs
      - KUBECONFIG=/home/kubefill/.kube/config
