####################################################################################################
# kubefill-dev
####################################################################################################
FROM kubefill-base
COPY kubefill /usr/local/bin/

USER root

RUN ln -s /usr/local/bin/kubefill /usr/local/bin/kubefill-server && \
    ln -s /usr/local/bin/kubefill /usr/local/bin/kubefill-reposerver

USER 999
