// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: reposerver/reposervice.proto

package reposerver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repo   string `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	RepoId string `protobuf:"bytes,2,opt,name=repoId,proto3" json:"repoId,omitempty"`
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SyncRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type SyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Commit string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SyncResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type SaveSshKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SshKey string `protobuf:"bytes,1,opt,name=sshKey,proto3" json:"sshKey,omitempty"`
	RepoId string `protobuf:"bytes,2,opt,name=repoId,proto3" json:"repoId,omitempty"`
}

func (x *SaveSshKeyRequest) Reset() {
	*x = SaveSshKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSshKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSshKeyRequest) ProtoMessage() {}

func (x *SaveSshKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSshKeyRequest.ProtoReflect.Descriptor instead.
func (*SaveSshKeyRequest) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{2}
}

func (x *SaveSshKeyRequest) GetSshKey() string {
	if x != nil {
		return x.SshKey
	}
	return ""
}

func (x *SaveSshKeyRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type SaveSshKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveSshKeyResponse) Reset() {
	*x = SaveSshKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSshKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSshKeyResponse) ProtoMessage() {}

func (x *SaveSshKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSshKeyResponse.ProtoReflect.Descriptor instead.
func (*SaveSshKeyResponse) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{3}
}

type RemoveSshKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoId string `protobuf:"bytes,1,opt,name=repoId,proto3" json:"repoId,omitempty"`
}

func (x *RemoveSshKeyRequest) Reset() {
	*x = RemoveSshKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSshKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSshKeyRequest) ProtoMessage() {}

func (x *RemoveSshKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSshKeyRequest.ProtoReflect.Descriptor instead.
func (*RemoveSshKeyRequest) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveSshKeyRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type RemoveSshKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveSshKeyResponse) Reset() {
	*x = RemoveSshKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSshKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSshKeyResponse) ProtoMessage() {}

func (x *RemoveSshKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSshKeyResponse.ProtoReflect.Descriptor instead.
func (*RemoveSshKeyResponse) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{5}
}

type ManifestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ManifestsRequest) Reset() {
	*x = ManifestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManifestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestsRequest) ProtoMessage() {}

func (x *ManifestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestsRequest.ProtoReflect.Descriptor instead.
func (*ManifestsRequest) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{6}
}

func (x *ManifestsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RepoDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoUrl string `protobuf:"bytes,1,opt,name=repoUrl,proto3" json:"repoUrl,omitempty"`
	RepoId  string `protobuf:"bytes,2,opt,name=repoId,proto3" json:"repoId,omitempty"`
}

func (x *RepoDirRequest) Reset() {
	*x = RepoDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoDirRequest) ProtoMessage() {}

func (x *RepoDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoDirRequest.ProtoReflect.Descriptor instead.
func (*RepoDirRequest) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{7}
}

func (x *RepoDirRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *RepoDirRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

type RepoDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *RepoDirResponse) Reset() {
	*x = RepoDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepoDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoDirResponse) ProtoMessage() {}

func (x *RepoDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoDirResponse.ProtoReflect.Descriptor instead.
func (*RepoDirResponse) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{8}
}

func (x *RepoDirResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PathsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PathsRequest) Reset() {
	*x = PathsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathsRequest) ProtoMessage() {}

func (x *PathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathsRequest.ProtoReflect.Descriptor instead.
func (*PathsRequest) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{9}
}

type PathsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoRoot   string `protobuf:"bytes,1,opt,name=repoRoot,proto3" json:"repoRoot,omitempty"`
	SshRoot    string `protobuf:"bytes,2,opt,name=sshRoot,proto3" json:"sshRoot,omitempty"`
	PrivateKey string `protobuf:"bytes,3,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
}

func (x *PathsResponse) Reset() {
	*x = PathsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathsResponse) ProtoMessage() {}

func (x *PathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathsResponse.ProtoReflect.Descriptor instead.
func (*PathsResponse) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{10}
}

func (x *PathsResponse) GetRepoRoot() string {
	if x != nil {
		return x.RepoRoot
	}
	return ""
}

func (x *PathsResponse) GetSshRoot() string {
	if x != nil {
		return x.SshRoot
	}
	return ""
}

func (x *PathsResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type ManifestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     *structpb.Struct `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	UiSchema *structpb.Struct `protobuf:"bytes,2,opt,name=ui_schema,json=uiSchema,proto3" json:"ui_schema,omitempty"`
	Schema   *structpb.Struct `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *ManifestsResponse) Reset() {
	*x = ManifestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reposerver_reposervice_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManifestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestsResponse) ProtoMessage() {}

func (x *ManifestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reposerver_reposervice_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestsResponse.ProtoReflect.Descriptor instead.
func (*ManifestsResponse) Descriptor() ([]byte, []int) {
	return file_reposerver_reposervice_proto_rawDescGZIP(), []int{11}
}

func (x *ManifestsResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ManifestsResponse) GetUiSchema() *structpb.Struct {
	if x != nil {
		return x.UiSchema
	}
	return nil
}

func (x *ManifestsResponse) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

var File_reposerver_reposervice_proto protoreflect.FileDescriptor

var file_reposerver_reposervice_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x70, 0x6f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x70,
	0x6f, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22,
	0x43, 0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x70, 0x6f, 0x49, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x26, 0x0a, 0x10, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x42, 0x0a, 0x0e, 0x52, 0x65, 0x70,
	0x6f, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x70, 0x6f, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x70, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x64, 0x22, 0x25, 0x0a,
	0x0f, 0x52, 0x65, 0x70, 0x6f, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x52, 0x6f, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x52, 0x6f, 0x6f,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x73, 0x68, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x73, 0x68, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0xa7, 0x01, 0x0a, 0x11,
	0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34,
	0x0a, 0x09, 0x75, 0x69, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x08, 0x75, 0x69, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x32, 0xc9, 0x03, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x17, 0x2e,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79,
	0x12, 0x1d, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x53, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65,
	0x79, 0x12, 0x1f, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e,
	0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f,
	0x44, 0x69, 0x72, 0x12, 0x1a, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x70, 0x6f, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x70,
	0x6f, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x18, 0x2e, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reposerver_reposervice_proto_rawDescOnce sync.Once
	file_reposerver_reposervice_proto_rawDescData = file_reposerver_reposervice_proto_rawDesc
)

func file_reposerver_reposervice_proto_rawDescGZIP() []byte {
	file_reposerver_reposervice_proto_rawDescOnce.Do(func() {
		file_reposerver_reposervice_proto_rawDescData = protoimpl.X.CompressGZIP(file_reposerver_reposervice_proto_rawDescData)
	})
	return file_reposerver_reposervice_proto_rawDescData
}

var file_reposerver_reposervice_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_reposerver_reposervice_proto_goTypes = []interface{}{
	(*SyncRequest)(nil),          // 0: reposerver.SyncRequest
	(*SyncResponse)(nil),         // 1: reposerver.SyncResponse
	(*SaveSshKeyRequest)(nil),    // 2: reposerver.SaveSshKeyRequest
	(*SaveSshKeyResponse)(nil),   // 3: reposerver.SaveSshKeyResponse
	(*RemoveSshKeyRequest)(nil),  // 4: reposerver.RemoveSshKeyRequest
	(*RemoveSshKeyResponse)(nil), // 5: reposerver.RemoveSshKeyResponse
	(*ManifestsRequest)(nil),     // 6: reposerver.ManifestsRequest
	(*RepoDirRequest)(nil),       // 7: reposerver.RepoDirRequest
	(*RepoDirResponse)(nil),      // 8: reposerver.RepoDirResponse
	(*PathsRequest)(nil),         // 9: reposerver.PathsRequest
	(*PathsResponse)(nil),        // 10: reposerver.PathsResponse
	(*ManifestsResponse)(nil),    // 11: reposerver.ManifestsResponse
	(*structpb.Struct)(nil),      // 12: google.protobuf.Struct
}
var file_reposerver_reposervice_proto_depIdxs = []int32{
	12, // 0: reposerver.ManifestsResponse.data:type_name -> google.protobuf.Struct
	12, // 1: reposerver.ManifestsResponse.ui_schema:type_name -> google.protobuf.Struct
	12, // 2: reposerver.ManifestsResponse.schema:type_name -> google.protobuf.Struct
	0,  // 3: reposerver.RepoService.Sync:input_type -> reposerver.SyncRequest
	2,  // 4: reposerver.RepoService.SaveSshKey:input_type -> reposerver.SaveSshKeyRequest
	4,  // 5: reposerver.RepoService.RemoveSshKey:input_type -> reposerver.RemoveSshKeyRequest
	6,  // 6: reposerver.RepoService.GetManifests:input_type -> reposerver.ManifestsRequest
	7,  // 7: reposerver.RepoService.GetRepoDir:input_type -> reposerver.RepoDirRequest
	9,  // 8: reposerver.RepoService.GetPaths:input_type -> reposerver.PathsRequest
	1,  // 9: reposerver.RepoService.Sync:output_type -> reposerver.SyncResponse
	3,  // 10: reposerver.RepoService.SaveSshKey:output_type -> reposerver.SaveSshKeyResponse
	5,  // 11: reposerver.RepoService.RemoveSshKey:output_type -> reposerver.RemoveSshKeyResponse
	11, // 12: reposerver.RepoService.GetManifests:output_type -> reposerver.ManifestsResponse
	8,  // 13: reposerver.RepoService.GetRepoDir:output_type -> reposerver.RepoDirResponse
	10, // 14: reposerver.RepoService.GetPaths:output_type -> reposerver.PathsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_reposerver_reposervice_proto_init() }
func file_reposerver_reposervice_proto_init() {
	if File_reposerver_reposervice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reposerver_reposervice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSshKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSshKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSshKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSshKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManifestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepoDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reposerver_reposervice_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManifestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reposerver_reposervice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reposerver_reposervice_proto_goTypes,
		DependencyIndexes: file_reposerver_reposervice_proto_depIdxs,
		MessageInfos:      file_reposerver_reposervice_proto_msgTypes,
	}.Build()
	File_reposerver_reposervice_proto = out.File
	file_reposerver_reposervice_proto_rawDesc = nil
	file_reposerver_reposervice_proto_goTypes = nil
	file_reposerver_reposervice_proto_depIdxs = nil
}
